---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

    - name: Get software for Python-based control.
      apt: "name={{ item }} state=installed"
      with_items:
        - curl
        - wget
        - python-apt
        - python-pycurl
        - build-essential

    - name: Disable the ufw firewall (since we use a simple iptables firewall).
      service: name=ufw state=stopped

    - name: Install postfix so Drupal can send emails.
      apt: name=postfix state=installed

    - name: Add repository for PHP 5.5.
      apt_repository: repo='ppa:ondrej/php5'
      when: php_version == "5.5"

    - name: Add repository for PHP 5.6.
      apt_repository: repo='ppa:ondrej/php5-5.6'
      when: php_version == "5.6"

    # Experimental.
    - name: Add repository for PHP 7.0.
      apt_repository: repo='ppa:ondrej/php-7.0'
      when: php_version == "7.0"

    - name: Update apt cache if needed.
      apt: update_cache=yes

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.memcached, tags: ['memcached'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.php-xdebug, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.drupal-console, tags: ['drupal-console'] }

  tasks:

    - git: repo=http://git.drupal.org/project/drupal.git
        dest=/home/vagrant/drupal8
        update=yes
        version=8.0.x

    - name: Disable default Apache site.
      command: a2dissite 000-default
      notify: restart webserver

    - name: Ensure other helpful software is installed.
      apt: "name={{ item }} state=present"
      with_items:
        - imagemagick
        - unzip